In [4]:
import gym
import numpy as np
import random 
from gym import Env
from gym.spaces import Discrete, Box
import math

In [5]:
value_i = np.zeros((12,12))
for i in range (7,12):
    for j in range (7,12):
        value_i[i][j] = 10
print(value_i)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 10. 10. 10. 10. 10.]
 [ 0.  0.  0.  0.  0.  0.  0. 10. 10. 10. 10. 10.]
 [ 0.  0.  0.  0.  0.  0.  0. 10. 10. 10. 10. 10.]
 [ 0.  0.  0.  0.  0.  0.  0. 10. 10. 10. 10. 10.]
 [ 0.  0.  0.  0.  0.  0.  0. 10. 10. 10. 10. 10.]]


In [6]:
def value_pos(a,b):
        x_grid = 0
        y_grid = 0
        #a is the x_position of the drone
        #b is the y_position of the drone
        if (a > 1100):
            a = 1100
        if (b > 1100):
            b = 1100
        while (x_grid < (a/100)):
            x_grid += 1
        while y_grid < (b/100):
            y_grid += 1
        # so now we get the grid postio of the drones in the env
#         x_grid = x_grid -1
#         y_grid = y_grid - 1
        inter = value_i[x_grid][y_grid]
        return inter
    
def dis_2_coor(x,y):
        result = math.sqrt((x[0]-x[1])**2 + (y[0]-y[1])**2)
        return result
    
# def transpose_func(arr):
#     arr_t = np.column_stack((arr,arr))
#     arr_t1,arr_t2 = np.hsplit(arr_t, 2)
#     return arr_t1


In [7]:
x = np.arange(8.0)
# print(np.split(x, [4,1,3]))
a = np.split(x, [4])
print(np.split(x, [6,7,8]))
# print(np.array_split(x, 4))
[x for x in a if x.size > 0]

[array([0., 1., 2., 3., 4., 5.]), array([6.]), array([7.]), array([], dtype=float64)]


[array([0., 1., 2., 3.]), array([4., 5., 6., 7.])]

In [8]:
class Environment(Env):
    CONSTANT_E_JOULES = 1
    def __init__(self):
        
        self.min = 0
        self.max = 1200
        self.N = 26
        self.sensing_range = 100
        
        self.action_space = Discrete(8)
        self.observation_space = Box(0, 1200, shape=(52,), dtype=np.float32)
        
        x_coor = []
        y_coor = []
#         interest_value = []
#         energy_consumption = []
        for i in range(self.N):
            x_coor.append(600)
            y_coor.append(600)
#             interest_value.append(value_pos(x_coor[i], y_coor[i]))
#             energy_consumption.append(0)
            
#         sum_e_c = 0
#         sum_iv = 0
            
#         for i in range(self.N):
#             sum_e_c += energy_consumption[i]
#             sum_iv += interest_value[i]
            
        self.state = np.hstack((x_coor, y_coor))
       
    
    def step(self, action):
        
        a = np.split(self.state,[self.N])
        a = [x for x in a if x.size > 0]
        x, y = a
                
        add_angle = 2*math.pi/self.N
        move_angle = np.zeros(self.N)
        if (action == 0):
            move_angle[0] = 0
            x[0] += 50
            for i in range(1,26):
                move_angle[i] = move_angle[i-1] + add_angle
                x[i] += 50*math.cos(move_angle[i]) 
                y[i] += 50*math.sin(move_angle[i])
                
        if (action == 1):
            move_angle[0] = math.pi/4
            x[0] += 50/math.sqrt(2)
            y[0] += 50/math.sqrt(2)
            for i in range(1,26):
                move_angle[i] = move_angle[i-1] + add_angle
                x[i] += 50*math.cos(move_angle[i]) 
                y[i] += 50*math.sin(move_angle[i])
         
        if (action == 2):
            move_angle[0] = math.pi/2
            y[0] += 50
            for i in range(1,26):
                move_angle[i] = move_angle[i-1] - add_angle
                x[i] += 50*math.cos(move_angle[i]) 
                y[i] += 50*math.sin(move_angle[i])
                
        if (action == 3):
            move_angle[0] = 3*math.pi/4
            x[0] -= 50/math.sqrt(2)
            y[0] += 50/math.sqrt(2) 
            for i in range(1,26):
                move_angle[i] = move_angle[i-1] - add_angle
                x[i] += 50*math.cos(move_angle[i]) 
                y[i] += 50*math.sin(move_angle[i])
                
        if (action == 4):
            move_angle[0] = math.pi
            x[0] -= 50/math.sqrt(2)
            for i in range(1,26):
                move_angle[i] = move_angle[i-1] - add_angle
                x[i] += 50*math.cos(move_angle[i]) 
                y[i] += 50*math.sin(move_angle[i])
                
        if (action == 5):
            move_angle[0] = 5*math.pi/4
            x[0] -= 50/math.sqrt(2)
            y[0] -= 50/math.sqrt(2)  
            for i in range(1,26):
                move_angle[i] = move_angle[i-1] - add_angle
                x[i] += 50*math.cos(move_angle[i]) 
                y[i] += 50*math.sin(move_angle[i])
                
        if (action == 6):
            move_angle[0] = 3*math.pi/2
            y[0] -= 50
            for i in range(1,26):
                move_angle[i] = move_angle[i-1] - add_angle
                x[i] += 50*math.cos(move_angle[i]) 
                y[i] += 50*math.sin(move_angle[i])
                
        if (action == 7):
            move_angle[0] = 7*math.pi/4
            x[0] += 50/math.sqrt(2)
            y[0] -= 50/math.sqrt(2)  
            for i in range(1,26):
                move_angle[i] = move_angle[i-1] - add_angle
                x[i] += 50*math.cos(move_angle[i]) 
                y[i] += 50*math.sin(move_angle[i])
                
        new_i_value = np.zeros(self.N)
        
        for i in range (self.N):
            if (x[i] > self.max):
                new_i_value[i] = value_pos(1200, y[i])
            if (y[i] > self.max):
                new_i_value[i] = value_pos(x[i], 1200)
            if (x[i] < self.min):
                new_i_value[i] = value_pos(0, y[i])
            if (y[i] < self.min):
                new_i_value[i] = value_pos(x[i], 0)
                # set as max,min
            else:
                new_i_value[i] = value_pos(x[i],y[i])
                
        new_ec = np.zeros(self.N)
        for i in range (self.N):
            new_ec[i] =  50 * self.CONSTANT_E_JOULES
            
        sum_i_value = 0
        sum_cov = 0
        sum_ec = 0
            
        for index in range (self.N):
            sum_i_value += new_i_value[index]
        
        for index in range (self.N):
            sum_ec += new_ec[index]
            
        def dis_2_uav (D_array):
            dis_between = []
            temp_array = D_array
            for i in range (self.N):
                for j in range (self.N):
                    dis_between.append(dis_2_coor(temp_array[i],D_array[j]))
            
            return dis_between
        
        coor_array = np.column_stack((x, y))
        dis_array = dis_2_uav(coor_array)
        # eleminate 0 value 
        dis_array = [i for i in dis_array if i != 0]
        
        d_threshold = math.sqrt(3) * self.sensing_range
        for i in range(len(dis_array)):
            dis_array[i] = max ((dis_array[i]-d_threshold),0)
            
#         print(dis_array)
        
        for i in range(len(dis_array)):
            sum_cov += dis_array[i]
            
#         print(sum_cov)
        reward =  sum_i_value + 0.001 * sum_cov - 0.001 * sum_ec
        
        
        self.state = np.hstack((x, y))
        
        for i in range (self.N):
            if (x[i] > self.max or y[i] > self.max or x[i] < self.min or y[i] < self.min):
                done = True
            else:
                done = False
        
        info = {}
#         print(self.state)
            
        return self.state, reward, done, info    
        
        
    def reset(self):
        x_coor = []
        y_coor = []
        
        
        for i in range(self.N):
            x_coor.append(600)
            y_coor.append(600)
       
        self.state = np.hstack((x_coor, y_coor))
        return self.state
    
        
    

In [9]:
env = Environment()

In [10]:
action = env.action_space.sample()
print(action)

1


In [11]:
episodes = 10
for episode in range(1, episodes+1):
    state = env.reset()
    done = False
    score = 0 
    
    while not done:
        action = env.action_space.sample()
        n_state, reward, done, info = env.step(action)
        score+=reward
    
    print('Episode:{} Score:{}'.format(episode, score))

Episode:1 Score:31321.413369211303
Episode:2 Score:100481.98770665313
Episode:3 Score:28595.77539723836
Episode:4 Score:102397.8404300774
Episode:5 Score:46633.29969276946
Episode:6 Score:166242.3814927544
Episode:7 Score:85080.62018280593
Episode:8 Score:19872.425728070775
Episode:9 Score:13913.055567763151
Episode:10 Score:49269.88849048967


In [12]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam

In [13]:
states = env.observation_space.shape
actions = env.action_space.n

In [14]:
print(actions)
states 

8


(52,)

In [18]:
def build_model(states, actions):
    model = Sequential()    
    model.add(Dense(24, activation='relu', input_shape=(1,52)))
    model.add(Dense(24, activation='relu'))
    model.add(Dense(8, activation='linear'))
    model.add(Flatten())
    return model

In [19]:
model = build_model(states, actions)

In [20]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 1, 24)             1272      
                                                                 
 dense_4 (Dense)             (None, 1, 24)             600       
                                                                 
 dense_5 (Dense)             (None, 1, 8)              200       
                                                                 
 flatten (Flatten)           (None, 8)                 0         
                                                                 
Total params: 2,072
Trainable params: 2,072
Non-trainable params: 0
_________________________________________________________________


In [29]:
from rl.agents import DQNAgent
from rl.policy import BoltzmannQPolicy
from rl.memory import SequentialMemory

In [30]:
def build_agent(model, actions):
    policy = BoltzmannQPolicy()
    memory = SequentialMemory(limit=50000, window_length=1)
    dqn = DQNAgent(model=model, memory=memory, policy=policy, 
                  nb_actions=actions, nb_steps_warmup=10, target_model_update=1e-2)
    return dqn

In [31]:
dqn = build_agent(model, actions)
dqn.compile(Adam(learning_rate=1e-3), metrics=['mae'])
dqn.fit(env, nb_steps=50000, visualize=False, verbose=1)

Training for 50000 steps ...
Interval 1 (0 steps performed)
    1/10000 [..............................] - ETA: 9:48 - reward: 58.7000

C:\Users\Admin\anaconda3\envs\testenv\lib\site-packages\keras\engine\training_v1.py:2079: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,
C:\Users\Admin\anaconda3\envs\testenv\lib\site-packages\rl\memory.py:37: UserWarning: Not enough entries to sample without replacement. Consider increasing your warm-up phase to avoid oversampling!
  warnings.warn('Not enough entries to sample without replacement. Consider increasing your warm-up phase to avoid oversampling!')


10000/10000 [==============================] - 60s 6ms/step - reward: 492.1843
173 episodes - episode_reward: 28405.573 [3536.312, 318062.131] - loss: 30069479.001 - mae: 42902.423 - mean_q: 58029.710

Interval 2 (10000 steps performed)
10000/10000 [==============================] - 60s 6ms/step - reward: 432.6291
178 episodes - episode_reward: 24310.452 [4370.583, 92840.645] - loss: 1655752448.000 - mae: 395079.844 - mean_q: 538033.000

Interval 3 (20000 steps performed)
10000/10000 [==============================] - 59s 6ms/step - reward: 438.1055
174 episodes - episode_reward: 25110.002 [5382.633, 110666.414] - loss: 94816935936.000 - mae: 3126702.000 - mean_q: 4313282.500

Interval 4 (30000 steps performed)
10000/10000 [==============================] - 60s 6ms/step - reward: 421.5550
181 episodes - episode_reward: 23346.342 [5070.422, 104245.323] - loss: 4260873371648.000 - mae: 21059136.000 - mean_q: 29167390.000

Interval 5 (40000 steps performed)
10000/10000 [==================

In [32]:
scores = dqn.test(env, nb_episodes=100, visualize=False)
print(np.mean(scores.history['episode_reward']))

Testing for 100 episodes ...
Episode 1: reward: 3536.312, steps: 13
Episode 2: reward: 3536.312, steps: 13
Episode 3: reward: 3536.312, steps: 13
Episode 4: reward: 3536.312, steps: 13
Episode 5: reward: 3536.312, steps: 13
Episode 6: reward: 3536.312, steps: 13
Episode 7: reward: 3536.312, steps: 13
Episode 8: reward: 3536.312, steps: 13
Episode 9: reward: 3536.312, steps: 13
Episode 10: reward: 3536.312, steps: 13
Episode 11: reward: 3536.312, steps: 13
Episode 12: reward: 3536.312, steps: 13
Episode 13: reward: 3536.312, steps: 13
Episode 14: reward: 3536.312, steps: 13
Episode 15: reward: 3536.312, steps: 13
Episode 16: reward: 3536.312, steps: 13
Episode 17: reward: 3536.312, steps: 13
Episode 18: reward: 3536.312, steps: 13
Episode 19: reward: 3536.312, steps: 13
Episode 20: reward: 3536.312, steps: 13
Episode 21: reward: 3536.312, steps: 13
Episode 22: reward: 3536.312, steps: 13
Episode 23: reward: 3536.312, steps: 13
Episode 24: reward: 3536.312, steps: 13
Episode 25: reward: 

In [34]:
_ = dqn.test(env, nb_episodes=15, visualize=False)

Testing for 15 episodes ...
Episode 1: reward: 3536.312, steps: 13
Episode 2: reward: 3536.312, steps: 13
Episode 3: reward: 3536.312, steps: 13
Episode 4: reward: 3536.312, steps: 13
Episode 5: reward: 3536.312, steps: 13
Episode 6: reward: 3536.312, steps: 13
Episode 7: reward: 3536.312, steps: 13
Episode 8: reward: 3536.312, steps: 13
Episode 9: reward: 3536.312, steps: 13
Episode 10: reward: 3536.312, steps: 13
Episode 11: reward: 3536.312, steps: 13
Episode 12: reward: 3536.312, steps: 13
Episode 13: reward: 3536.312, steps: 13
Episode 14: reward: 3536.312, steps: 13
Episode 15: reward: 3536.312, steps: 13
